language: node_js
node_js:
  - "7"
before_script:
- npm install -g gulp
- npm install
script:
- gulp dist
- gulp critical
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  on:
    branch: develop
  target_branch: master
  fqdn: staceyfenton.com
  github_token:
    secure: LnhYxUjrfAQjA8qmdbVn82/lykjpXSL+y9+m5fx/wMEKeAwlvDIWAhbPrMxVCZ1HlgUXE/oAGtP3WUP2sqYK0MJkrCYBH4cWkJn1ql7F4ekXImtFxWcelxnZ1WK1/mxWfSNUhX/Vhy9YND+WiEY7uNwGcxx5VQCIaPOjUoniZN6YqJIVXJ2juFHw5Lc+ovFqVARRk1K+a2oyWcHIl/tQIpLY8x71lNFhqYeSy0VsFNyOXBVDVkW9lxVY0xHniyD+HUuwxChSeUkn/xGFni4JkWi7QhiURdEs8U5X926Fmx7/0WekPDBrkKXH3bXxeuBq7p39kAnMsIFnkENiV/VrRh81yYkuMhuiCiqvkpUno+CkDL6vczNas8EYVLLEb0jy1J9v6plxWYPpk2OW4JfsvN3wQ+I9GbfkHeijC3vzXHzgM6rrEZLXDO0Hi7CDmzt4cAVAKOTm29JxGaxtUdNnUggehX4G3mrVzRn4bnTp8E6gviS/DgU2o4pqLDmbB0onEP3A4KQgLt5zHE01CId9oob6fjrqVGZeERDrT/03iOOBEKCSvjOIrTJ7GO4S9sccogasRg8qjl6tOoXkXEXgBVrsj+Q0suUF4YWdxlv2kLLog5aKeQ7nd/8ddOxzcKT3amwCVSHP+NEDLxWkRFuchDkghl9ZW/0csdpeB9kRltk=
