language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
- npm install
script:
- gulp dist
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  on:
    branch: develop
  target_branch: master
  github_token:
    secure: CtJA1b5zN9E4qryqSJw0wI/W+h+jBXs0/WPJd5pquA2NZBtV7CixdnT5ZhIZ7k+D7XbKnqHWY2HqNCsISHPwWQYhAZLnGxviPkHn2bVVjUs1Ugamh1ZT7jrrh6qnVcQFFNprlnxIEt5eDic4a/cRvnabl8/x52YD6qTaqTy2uPUFIREVKkKaai9QL1+cBE5TYROHnWa52tP48GrEaCmiYwypEgvCL9TjWL3bKOsYDUCDCpR6qsHi6Y1WuqwZyTf5o4Qf4p0OnEx+y/m1mZEjCjWvXfAI9RX6TRh9vBPhkd8Oz8xYbNM8SRUUCIQWG3L9Vvz0wQsK6q3GmN8varTus2QM0cUDH93V8xkUew+aGhR9I9ABpi97wW/eJBmfGWNhL1IDrkuHdtyp3jGTf9DGEcrblcfHeRFbFEcq56BGqF2Qdp5S4vg1+rSEYFrA5QMpkpsdyRj5AM6e3HiNFI/+8kpfWDgY//8tJo9k3FZqiZjZr8smpzGFcHbZU/KHAhEKq8C7TDu+zYBzw5XeCpiq69wixYIRfzguxHqGMo2lj1+9HyfFrysU+Vs7k9tx4MTffSjlFe1bdbMJP6hWOdu3wVfOrrmxv4JFl545pq1O+BrLFvJygNpKc5ZUGA7ih4u0brwvOlyOVawJWVpaocyGvv/5UEOs9eOO6fU1l4LguXo=
