language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g gulp
  - npm install
script: 
  - gulp dist
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: develop
  target_branch: master