name: Deploy Site

on:
  workflow_dispatch:
  push:
    branches:
    - v4 # Only trigger on the v4 branch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate static site
    steps:    
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      - run: npm install
      - run: npm run export
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        publish_branch: master